restart-message-format: '&4[Notice] &6» &cServer restarting in &e%time% &c%unit%!' # Restart message
restart-cancel-message-format: '&4[Notice] &6» &2Restart canceled by operator!' # Restart canceled message
restart-buffer: 240 # Minutes to wait after server startup for restart, put -1 for no restart
restart-duration: 60 # How long the restart should last

plugins-to-load:
  - "core"

plugins-to-save:
  - "guilds"
  - "core"
  - "bank"
  - "professions"
  - "items"
  - "quests"
  - "achievements"

tips:
  messages:
    - '&5[Runic Realms] &6» &dUse the quest book in your hotbar for info about your current quests!'
    - '&5[Runic Realms] &6» &dWhen running dungeons, get some friends to help you- it won''t be easy!'
    - '&5[Runic Realms] &6» &dType &e/ch &eglobal&d/&elocal&d/&eparty&d/&eguild &dto enter different chat channels!'
    - '&5[Runic Realms] &6» &dWhen you die, all items that are not in your hotbar or armor slots are put in a gravestone you can collect them from!'
    - '&5[Runic Realms] &6» &dCheck out our Discord server to seek help and more information!'
    - '&5[Runic Realms] &6» &dType &e/map &dto get a link to our online map of the whole world!'
    - '&5[Runic Realms] &6» &dVisit a Runic Mage to reset your skill points!'
    - '&5[Runic Realms] &6» &dUse &e/toggletips &dto disable game tips!'
    - '&5[Runic Realms] &6» &dStarting at level 25, flag for PvP as an &cOutlaw &dto receive an exp bonus!'
    - '&5[Runic Realms] &6» &dDid you know? You can hover over a player''s name in chat to see additional info!'
    - '&5[Runic Realms] &6» &dType &e[item] &din chat while holding an item to link its tooltip!'
    - '&5[Runic Realms] &6» &dType &e[coords] &din chat while to show your location!'
    - '&5[Runic Realms] &6» &dType &e/whois <player> &dto get info about a player''s class!'
    - '&5[Runic Realms] &6» &dType &e/roll &dto roll the dice!'
  delay: 300
  interval: 300