restart-message-format: '&4[Notice] &cServer restarting in &e%time% &c%unit%!' # Restart message
restart-cancel-message-format: '&4[Notice] &2Restart canceled by operator!' # Restart canceled message
restart-buffer: 110 # Minutes to wait after server startup for restart, put -1 for no restart
restart-duration: 10 # How long the restart should last

plugins-to-load:
- "trade-market"
- "guilds"
- "npcs"

plugins-to-save:
- "guilds"
- "core"
- "bank"

tips:
  messages:
  - '&5[RunicRealms] &6» &aUse the quest book in your hotbar for info about your current quests!'
  - '&5[RunicRealms] &6» &aWhen running dungeons, get some friends to help you-- it won''t be easy!'
  - '&5[RunicRealms] &6» &aType &e/global &aor &e/local &ato enter different chat channels!'
  - '&5[RunicRealms] &6» &aWhen you die, all items that are not in your hotbar or armor slots will be dropped on the floor!'
  - '&5[RunicRealms] &6» &aCheck out our Discord server to seek help and more information!'
  - '&5[RunicRealms] &6» &aType &e/map &ato get a link to our online map of the whole world!'
  - '&5[RunicRealms] &6» &aVisit an Artifact Mage to reforge your artifacts and weapons into one new item!'
  - '&5[RunicRealms] &6» &aUse &e/toggletips &ato stop seeing these messages!'
  delay: 300
  interval: 300