restart-message-format: '&4[Notice] &cServer restarting in &e%time% &c%unit%!' # Restart message
restart-cancel-message-format: '&4[Notice] &2Restart canceled by operator!' # Restart canceled message
restart-buffer: 110 # Minutes to wait after server startup for restart, put -1 for no restart
restart-duration: 10 # How long the restart should last

plugins-to-load:
- "trade-market"
- "guilds"

plugins-to-save:
- "guilds"
- "core"
- "bank"

recurring-messages:
  1:
    message: "&4[Notice] &cOur bank system is currently experiencing some issues. If you use it, &eyou may lose items&c."
    interval: 300