name: RunicRestart
description: Runic Realms Restart Plugin, by Excel
version: 1.0
main: com.runicrealms.runicrestart.Plugin
api-version: 1.13
commands:
  runicrestart:
    description: Restarts the server