name: RunicRestart
description: Runic Realms Restart Plugin, by Excel
version: 1.0
main: com.runicrealms.runicrestart.Plugin
api-version: 1.13
loadbefore: [RunicCharacters, RunicTradeMarket, RunicGuilds]
commands:
  runicrestart:
    description: Restarts the server
  runicstop:
    description: Restarts the server
    aliases: [rstop]
  runicsave:
      description: Saves the server
      aliases: [rsave]